<h2>DATA PREPROCESSING</h2>

<h3>IDS_ALLCountries_Data</h3>

In [95]:
import pandas as pd
import numpy as np

In [96]:
df_IDS_ALLCountries_Data = pd.read_csv('IDS_ALLCountries_Data.csv', encoding='latin1')

In [97]:
df_IDS_ALLCountries_Data.isnull().sum()

Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
Series Code                  5
2000                     13493
2001                     13549
2002                     13721
2003                     13982
2004                     13788
2005                     13846
2006                     13589
2007                     13338
2008                     13486
2009                     13215
2010                     13222
2011                     13903
2012                     13975
2013                     13604
2014                     12479
2015                     12552
2016                     12791
2017                     12650
2018                     12687
2019                     12490
2020                     12027
2021                     12256
2022                     12262
2023                     12342
2024                     12393
2025                     50128
2026                     50223
2027                     50361
2028                     50551
2029                     50845
2030                     51016
2031                     51212
2032                     51417
dtype: int64

<p>
An analysis of missing values revealed that the columns representing the years 2025 to 2032 contain over 50,000 null records each. Since these columns have insufficient data and are unlikely to contribute meaningful insights to the analysis, they were excluded from the dataset to improve data quality and reduce unnecessary complexity.
<p>

In [98]:
df_IDS_ALLCountries_Data = df_IDS_ALLCountries_Data.drop(columns = ['2025','2026','2027','2028','2029','2030','2031','2032'])

In [99]:
df_IDS_ALLCountries_Data.isnull().sum()

Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
Series Code                  5
2000                     13493
2001                     13549
2002                     13721
2003                     13982
2004                     13788
2005                     13846
2006                     13589
2007                     13338
2008                     13486
2009                     13215
2010                     13222
2011                     13903
2012                     13975
2013                     13604
2014                     12479
2015                     12552
2016                     12791
2017                     12650
2018                     12687
2019                     12490
2020                     12027
2021                     12256
2022                     12262
2023                     12342
2024                     12393
dtype: int64

In [100]:
df_IDS_ALLCountries_Data[df_IDS_ALLCountries_Data.duplicated()]

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2000,2001,2002,2003,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
62979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<h5> Two duplicate records were identified in the dataset. As all fields in these records contained null values and did not contribute any meaningful information, they were removed during the data cleaning process.</h5>

In [101]:
df_IDS_ALLCountries_Data.drop([62979,62980], inplace = True)

In [102]:
df_IDS_ALLCountries_Data[df_IDS_ALLCountries_Data.duplicated()]

Empty DataFrame
Columns: [Country Name, Country Code, Counterpart-Area Name, Counterpart-Area Code, Series Name, Series Code, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
Index: []

[0 rows x 31 columns]

In [103]:
year_cols = [str(year) for year in range(2000, 2025)]

df_IDS_ALLCountries_Data = pd.melt(
    df_IDS_ALLCountries_Data,
    id_vars=[col for col in df_IDS_ALLCountries_Data.columns if col not in year_cols],
    value_vars=year_cols,
    var_name='Year',
    value_name='Value'
)

In [104]:
df_IDS_ALLCountries_Data.columns

Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', 'Year', 'Value'],
      dtype='object')

In [105]:
df_IDS_ALLCountries_Data

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,Year,Value
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,2000,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,2000,NaN
...,...,...,...,...,...,...,...,...
1574520,Zimbabwe,ZWE,World,WLD,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2024,0.000000e+00
1574521,Zimbabwe,ZWE,World,WLD,"Use of IMF credit and SDR allocations (DOD, cu...",DT.DOD.DIMF.CD,2024,1.325023e+09
1574522,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN
1574523,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,2024,NaN
1574524,Last Updated: 12/03/2025,NaN,NaN,NaN,NaN,NaN,2024,NaN

In [106]:
df_IDS_ALLCountries_Data.columns

Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', 'Year', 'Value'],
      dtype='object')

In [107]:
df_IDS_ALLCountries_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1574525 entries, 0 to 1574524
Data columns (total 8 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Country Name           1574500 non-null  object
 1   Country Code           1574450 non-null  object
 2   Counterpart-Area Name  1574450 non-null  object
 3   Counterpart-Area Code  1574450 non-null  object
 4   Series Name            1574450 non-null  object
 5   Series Code            1574450 non-null  object
 6   Year                   1574525 non-null  object
 7   Value                  1246935 non-null  float64
dtypes: float64(1), object(7)
memory usage: 96.1+ MB

In [108]:
df_IDS_ALLCountries_Data = df_IDS_ALLCountries_Data.dropna(subset=['Value'])

In [109]:
df_IDS_ALLCountries_Data.nunique()

Country Name                134
Country Code                134
Counterpart-Area Name         1
Counterpart-Area Code         1
Series Name                 576
Series Code                 576
Year                         25
Value                    670162
dtype: int64

In [110]:
cols_to_drop = df_IDS_ALLCountries_Data.columns[
    df_IDS_ALLCountries_Data.nunique() == 1
]

df_IDS_ALLCountries_Data=df_IDS_ALLCountries_Data.drop(columns=cols_to_drop)

In [129]:
df_IDS_ALLCountries_Data

,Country Name,Country Code,Series Name,Series Code,Year,Value
297,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,1.054540e+01
298,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,1.054540e+01
299,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,0.000000e+00
300,Albania,ALB,Average grant element on new external debt com...,DT.GRE.DPPG,2000,2.576090e+01
301,Albania,ALB,Average grant element on new external debt com...,DT.GRE.OFFT,2000,2.576090e+01
...,...,...,...,...,...,...
1574517,Zimbabwe,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,2024,6.881084e+08
1574518,Zimbabwe,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,2024,6.350490e+06
1574519,Zimbabwe,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,2024,6.944589e+08
1574520,Zimbabwe,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2024,0.000000e+00
1574521,Zimbabwe,ZWE,"Use of IMF credit and SDR allocations (DOD, cu...",DT.DOD.DIMF.CD,2024,1.325023e+09

<p>
The columns <b>Counterpart-Area Name</b> and <b>Counterpart-Area Code</b> each contain only a single unique value across all records. As these columns do not provide any variability or contribute meaningful information for analysis, they were removed from the dataset to reduce redundancy and improve data efficiency.
<p>

In [112]:
df_IDS_ALLCountries_Data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1246935 entries, 297 to 1574521
Data columns (total 6 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Country Name  1246935 non-null  object
 1   Country Code  1246935 non-null  object
 2   Series Name   1246935 non-null  object
 3   Series Code   1246935 non-null  object
 4   Year          1246935 non-null  object
 5   Value         1246935 non-null  float64
dtypes: float64(1), object(5)
memory usage: 66.6+ MB

<p>The dataset originally contained separate columns for each year from 2000 to 2024, resulting in a large number of columns. To improve data organization and make the dataset more suitable for analysis and visualization, these year-specific columns were transformed into a long format using a single Year column and a corresponding Value column.</p>

<p>In this transformation, the year information from the columns 2000–2024 was consolidated into the Year column, while the corresponding data values were stored in the Value column. This significantly reduced the number of columns in the dataset, although the number of rows increased as each year-value pair became a separate record.</p>

<p>Furthermore, the Value column represents the primary measure of interest in this dataset and is essential for meaningful analysis. Therefore, all records containing null (missing) values in the Value column were removed to ensure data quality and maintain the reliability of subsequent analysis and visualizations.</p>

In [113]:
df_IDS_ALLCountries_Data.isnull().sum()

Country Name    0
Country Code    0
Series Name     0
Series Code     0
Year            0
Value           0
dtype: int64

In [114]:
df_IDS_ALLCountries_Data.shape

(1246935, 6)

In [124]:
df_IDS_ALLCountries_Data.to_csv('Cleaned_IDS_ALLCountries_Data.csv',index = False)

<h3>Country_series</h3>

In [20]:
df_country_series = pd.read_csv('Country-Series - Metadata.csv', encoding='latin1')

In [21]:
df_country_series.nunique()

Type              1
Country Code    131
Series Code       7
Description     130
dtype: int64

In [22]:
df_country_series=df_country_series.drop(columns = 'Type')

In [23]:
df_country_series ['Series Code'] = df_country_series ['Series Code'].str.extract(r'\(([^()]*)\)$')

In [24]:
df_country_series[['Country Name', 'Country Code']] = (df_country_series['Country Code'].str.extract(r'^(.*?)\s*\((.*?)\)$'))

In [26]:
df_country_series.columns

Index(['Country Code', 'Series Code', 'Description', 'Country Name'], dtype='object')

In [27]:
df_country_series = df_country_series [['Country Name','Country Code', 'Series Code', 'Description']]

In [28]:
df_country_series

,Country Name,Country Code,Series Code,Description
0,Afghanistan,AFG,BX.KLT.DINV.CD.DT,Data on Foreign Direct Investment are based on...
1,Afghanistan,AFG,SP.POP.TOTL,Data source: United Nations World Population P...
2,Afghanistan,AFG,DT.DOD.DECT.CD,"Long-term public and publicly guaranteed, long..."
3,Angola,AGO,DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
4,Angola,AGO,SP.POP.TOTL,Data source: United Nations World Population P...
...,...,...,...,...
370,Zambia,ZMB,SP.POP.TOTL,Data source: United Nations World Population P...
371,Zambia,ZMB,DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
372,Zimbabwe,ZWE,DT.DOD.DECT.CD,Long-term public and publicly guaranteed and l...
373,Zimbabwe,ZWE,SP.POP.TOTL,Data source: United Nations World Population P...
374,Zimbabwe,ZWE,BX.KLT.DINV.CD.DT,Data on Foreign Direct Investment are based on...

In [29]:
df_country_series.isnull().sum()

Country Name    0
Country Code    0
Series Code     0
Description     0
dtype: int64

In [125]:
df_country_series.to_csv('Cleaned_Country-Series - Metadata.csv',index = False)

<h3>IDS_CountryMetaData</h3>

In [41]:
df_IDS_CountryMetaData = pd.read_csv('IDS_CountryMetaData.csv', encoding='latin1')

In [42]:
df_IDS_CountryMetaData.head()

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,AFG,Islamic State of Afghanistan,Low income,Middle East & North Africa,IDA,HIPC,Afghan afghani,1979,Multiple Indicator Cluster Survey 2022-2023,The reporting period for national accounts dat...,...,"Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,2000.0,AF,AF,Afghanistan,Afghanistan
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2023,Demographic and Health Survey 2017 - 2018,NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
2,DZA,People's Democratic Republic of Algeria,Upper middle income,Middle East & North Africa,IBRD,NaN,Algerian dinar,2022,Multiple Indicator Cluster Survey 2018-2019,NaN,...,"Integrated household survey (IHS), 2011",NaN,NaN,2010.0,2017.0,2012.0,DZ,DZ,Algeria,Algeria
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa,IBRD,NaN,Angolan kwanza,2014,Demographic and Health Survey 2015/16,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,2005.0,AO,AO,Angola,Angola
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2022,Multiple Indicator Cluster Survey 2019-2020,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina

In [45]:
df_IDS_CountryMetaData = df_IDS_CountryMetaData[[ 'Short Name','Code','Income Group', 'Region', 'Lending category','Other groups']]

In [48]:
df_IDS_CountryMetaData.rename(columns = {"Short Name" : "Country Name", "Other groups" : "Is_HIPC"}, inplace = True)

In [51]:
df_IDS_CountryMetaData['Is_HIPC'] = df_IDS_CountryMetaData['Is_HIPC'].fillna('No')

In [53]:
df_IDS_CountryMetaData['Is_HIPC'] = df_IDS_CountryMetaData['Is_HIPC'].replace('HIPC', 'Yes')

In [54]:
df_IDS_CountryMetaData.head()

,Country Name,Code,Income Group,Region,Lending category,Is_HIPC
0,Afghanistan,AFG,Low income,Middle East & North Africa,IDA,Yes
1,Albania,ALB,Upper middle income,Europe & Central Asia,IBRD,No
2,Algeria,DZA,Upper middle income,Middle East & North Africa,IBRD,No
3,Angola,AGO,Lower middle income,Sub-Saharan Africa,IBRD,No
4,Argentina,ARG,Upper middle income,Latin America & Caribbean,IBRD,No

In [66]:
df_IDS_CountryMetaData = df_IDS_CountryMetaData.dropna(subset=['Region'])

In [67]:
df_IDS_CountryMetaData[df_IDS_CountryMetaData['Region'].isnull()]

Empty DataFrame
Columns: [Country Name, Code, Income Group, Region, Lending category, Is_HIPC]
Index: []

In [68]:
df_IDS_CountryMetaData.nunique()

Country Name        120
Code                120
Income Group          4
Region                6
Lending category      3
Is_HIPC               2
dtype: int64

In [78]:
df_IDS_CountryMetaData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119 entries, 0 to 133
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country Name      119 non-null    object
 1   Code              119 non-null    object
 2   Income Group      119 non-null    object
 3   Region            119 non-null    object
 4   Lending category  119 non-null    object
 5   Is_HIPC           119 non-null    object
dtypes: object(6)
memory usage: 6.5+ KB

In [70]:
df_IDS_CountryMetaData[df_IDS_CountryMetaData['Income Group'].isnull()]

   Country Name Code Income Group              Region Lending category Is_HIPC
39     Ethiopia  ETH          NaN  Sub-Saharan Africa              IDA     Yes

In [76]:
df_IDS_CountryMetaData = df_IDS_CountryMetaData.dropna(subset=['Income Group'])

In [77]:
df_IDS_CountryMetaData

,Country Name,Code,Income Group,Region,Lending category,Is_HIPC
0,Afghanistan,AFG,Low income,Middle East & North Africa,IDA,Yes
1,Albania,ALB,Upper middle income,Europe & Central Asia,IBRD,No
2,Algeria,DZA,Upper middle income,Middle East & North Africa,IBRD,No
3,Angola,AGO,Lower middle income,Sub-Saharan Africa,IBRD,No
4,Argentina,ARG,Upper middle income,Latin America & Caribbean,IBRD,No
...,...,...,...,...,...,...
129,Vanuatu,VUT,Lower middle income,East Asia & Pacific,IDA,No
130,Viet Nam,VNM,Lower middle income,East Asia & Pacific,IBRD,No
131,"Yemen, Republic of",YEM,Low income,Middle East & North Africa,IDA,No
132,Zambia,ZMB,Lower middle income,Sub-Saharan Africa,IDA,Yes
133,Zimbabwe,ZWE,Lower middle income,Sub-Saharan Africa,Blend,No

In [79]:
df_IDS_CountryMetaData.reset_index(drop=True, inplace=True)

In [80]:
df_IDS_CountryMetaData

,Country Name,Code,Income Group,Region,Lending category,Is_HIPC
0,Afghanistan,AFG,Low income,Middle East & North Africa,IDA,Yes
1,Albania,ALB,Upper middle income,Europe & Central Asia,IBRD,No
2,Algeria,DZA,Upper middle income,Middle East & North Africa,IBRD,No
3,Angola,AGO,Lower middle income,Sub-Saharan Africa,IBRD,No
4,Argentina,ARG,Upper middle income,Latin America & Caribbean,IBRD,No
...,...,...,...,...,...,...
114,Vanuatu,VUT,Lower middle income,East Asia & Pacific,IDA,No
115,Viet Nam,VNM,Lower middle income,East Asia & Pacific,IBRD,No
116,"Yemen, Republic of",YEM,Low income,Middle East & North Africa,IDA,No
117,Zambia,ZMB,Lower middle income,Sub-Saharan Africa,IDA,Yes
118,Zimbabwe,ZWE,Lower middle income,Sub-Saharan Africa,Blend,No

df_IDS_CountryMetaData.info()

In [82]:
df_IDS_CountryMetaData.isnull().sum()

Country Name        0
Code                0
Income Group        0
Region              0
Lending category    0
Is_HIPC             0
dtype: int64

In [126]:
df_IDS_CountryMetaData.to_csv('Cleaned_IDS_CountryMetaData.csv',index = False)

<h3>IDS_FootNoteMetaData</h3>

In [83]:
df_IDS_FootNoteMetaData = pd.read_csv('IDS_FootNoteMetaData.csv', encoding='latin1')

In [128]:
df_IDS_FootNoteMetaData

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2024 (YR2024),Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2023 (YR2023),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2021 (YR2021),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2022 (YR2022),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...
...,...,...,...,...,...
2668,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1974 (YR1974),Source: United Nations Conference on Trade and...
2669,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1970 (YR1970),Source: United Nations Conference on Trade and...
2670,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1973 (YR1973),Source: United Nations Conference on Trade and...
2671,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1971 (YR1971),Source: United Nations Conference on Trade and...
2672,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1976 (YR1976),Source: United Nations Conference on Trade and...

In [84]:
df_IDS_FootNoteMetaData.columns

Index(['Type', 'Country Code', 'Series Code', 'Time Code', 'Description'], dtype='object')

<h3>Irrevelant columns for Debt Analysis</h3>

<h3>IDS_SeriesMetaData</h3>

In [86]:
df_IDS_SeriesMetaData = pd.read_csv('IDS_SeriesMetaData.csv',encoding='latin1')

In [87]:
df_IDS_SeriesMetaData.columns

Index(['Code', 'License Type', 'Indicator Name', 'Short definition',
       'Long definition', 'Source', 'Topic', 'Dataset', 'Periodicity',
       'Aggregation method', 'Limitations and exceptions', 'General comments'],
      dtype='object')

In [90]:
df_IDS_SeriesMetaData = df_IDS_SeriesMetaData[['Code','Indicator Name','Long definition']]

In [91]:
df_IDS_SeriesMetaData

,Code,Indicator Name,Long definition
0,DT.GPA.DPPG,Average grace period on new external debt comm...,Grace period is the period from the date of si...
1,DT.GPA.OFFT,Average grace period on new external debt comm...,Grace period is the period from the date of si...
2,DT.GPA.PRVT,Average grace period on new external debt comm...,Grace period is the period from the date of si...
3,DT.GRE.DPPG,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...
4,DT.GRE.OFFT,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...
...,...,...,...
569,FI.RES.TOTL.MO,Total reserves in months of imports,Total reserves comprise holdings of monetary g...
570,DT.UND.OFFT.CD,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...
571,DT.UND.PRVT.CD,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...
572,DT.UND.DPPG.CD,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...
573,DT.DOD.DIMF.CD,"Use of IMF credit (DOD, current US$)",Use of IMF Credit: Data related to the operati...

In [92]:
df_IDS_SeriesMetaData.isnull().sum()

Code               0
Indicator Name     0
Long definition    0
dtype: int64

In [127]:
df_IDS_SeriesMetaData.to_csv('Cleaned_IDS_SeriesMetaData.csv',index = False)

<h2>All Provided datasets</h2>

In [130]:
df_IDS_ALLCountries_Data

,Country Name,Country Code,Series Name,Series Code,Year,Value
297,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,1.054540e+01
298,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,1.054540e+01
299,Albania,ALB,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,0.000000e+00
300,Albania,ALB,Average grant element on new external debt com...,DT.GRE.DPPG,2000,2.576090e+01
301,Albania,ALB,Average grant element on new external debt com...,DT.GRE.OFFT,2000,2.576090e+01
...,...,...,...,...,...,...
1574517,Zimbabwe,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,2024,6.881084e+08
1574518,Zimbabwe,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,2024,6.350490e+06
1574519,Zimbabwe,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,2024,6.944589e+08
1574520,Zimbabwe,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2024,0.000000e+00
1574521,Zimbabwe,ZWE,"Use of IMF credit and SDR allocations (DOD, cu...",DT.DOD.DIMF.CD,2024,1.325023e+09

In [131]:
df_IDS_SeriesMetaData

,Code,Indicator Name,Long definition
0,DT.GPA.DPPG,Average grace period on new external debt comm...,Grace period is the period from the date of si...
1,DT.GPA.OFFT,Average grace period on new external debt comm...,Grace period is the period from the date of si...
2,DT.GPA.PRVT,Average grace period on new external debt comm...,Grace period is the period from the date of si...
3,DT.GRE.DPPG,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...
4,DT.GRE.OFFT,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...
...,...,...,...
569,FI.RES.TOTL.MO,Total reserves in months of imports,Total reserves comprise holdings of monetary g...
570,DT.UND.OFFT.CD,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...
571,DT.UND.PRVT.CD,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...
572,DT.UND.DPPG.CD,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...
573,DT.DOD.DIMF.CD,"Use of IMF credit (DOD, current US$)",Use of IMF Credit: Data related to the operati...

In [133]:
df_country_series

,Country Name,Country Code,Series Code,Description
0,Afghanistan,AFG,BX.KLT.DINV.CD.DT,Data on Foreign Direct Investment are based on...
1,Afghanistan,AFG,SP.POP.TOTL,Data source: United Nations World Population P...
2,Afghanistan,AFG,DT.DOD.DECT.CD,"Long-term public and publicly guaranteed, long..."
3,Angola,AGO,DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
4,Angola,AGO,SP.POP.TOTL,Data source: United Nations World Population P...
...,...,...,...,...
370,Zambia,ZMB,SP.POP.TOTL,Data source: United Nations World Population P...
371,Zambia,ZMB,DT.DOD.DECT.CD,Long-term public and publicly guaranteed debt ...
372,Zimbabwe,ZWE,DT.DOD.DECT.CD,Long-term public and publicly guaranteed and l...
373,Zimbabwe,ZWE,SP.POP.TOTL,Data source: United Nations World Population P...
374,Zimbabwe,ZWE,BX.KLT.DINV.CD.DT,Data on Foreign Direct Investment are based on...

In [134]:
df_IDS_CountryMetaData

,Country Name,Code,Income Group,Region,Lending category,Is_HIPC
0,Afghanistan,AFG,Low income,Middle East & North Africa,IDA,Yes
1,Albania,ALB,Upper middle income,Europe & Central Asia,IBRD,No
2,Algeria,DZA,Upper middle income,Middle East & North Africa,IBRD,No
3,Angola,AGO,Lower middle income,Sub-Saharan Africa,IBRD,No
4,Argentina,ARG,Upper middle income,Latin America & Caribbean,IBRD,No
...,...,...,...,...,...,...
114,Vanuatu,VUT,Lower middle income,East Asia & Pacific,IDA,No
115,Viet Nam,VNM,Lower middle income,East Asia & Pacific,IBRD,No
116,"Yemen, Republic of",YEM,Low income,Middle East & North Africa,IDA,No
117,Zambia,ZMB,Lower middle income,Sub-Saharan Africa,IDA,Yes
118,Zimbabwe,ZWE,Lower middle income,Sub-Saharan Africa,Blend,No

In [135]:
df_IDS_FootNoteMetaData

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2024 (YR2024),Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2023 (YR2023),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2021 (YR2021),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2022 (YR2022),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...
...,...,...,...,...,...
2668,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1974 (YR1974),Source: United Nations Conference on Trade and...
2669,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1970 (YR1970),Source: United Nations Conference on Trade and...
2670,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1973 (YR1973),Source: United Nations Conference on Trade and...
2671,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1971 (YR1971),Source: United Nations Conference on Trade and...
2672,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1976 (YR1976),Source: United Nations Conference on Trade and...

In [136]:
df_IDS_SeriesMetaData

,Code,Indicator Name,Long definition
0,DT.GPA.DPPG,Average grace period on new external debt comm...,Grace period is the period from the date of si...
1,DT.GPA.OFFT,Average grace period on new external debt comm...,Grace period is the period from the date of si...
2,DT.GPA.PRVT,Average grace period on new external debt comm...,Grace period is the period from the date of si...
3,DT.GRE.DPPG,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...
4,DT.GRE.OFFT,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...
...,...,...,...
569,FI.RES.TOTL.MO,Total reserves in months of imports,Total reserves comprise holdings of monetary g...
570,DT.UND.OFFT.CD,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...
571,DT.UND.PRVT.CD,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...
572,DT.UND.DPPG.CD,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...
573,DT.DOD.DIMF.CD,"Use of IMF credit (DOD, current US$)",Use of IMF Credit: Data related to the operati...

<h2> Finalizing Tables based on the understanding of the provided dataset</h2>

In [144]:
df_IDS_ALLCountries_Data['Country Name'].nunique

119

In [138]:
df_IDS_ALLCountries_Data['Country Code'] = (
    df_IDS_ALLCountries_Data['Country Code'].astype(str).str.strip()
)

df_IDS_CountryMetaData['Code'] = (
    df_IDS_CountryMetaData['Code'].astype(str).str.strip()
)

In [139]:
extra = (
    set(df_IDS_ALLCountries_Data['Country Code'].unique())
    - set(df_IDS_CountryMetaData['Code'].unique())
)

print(sorted(extra))

['EAP', 'ECA', 'ETH', 'IDA', 'IDX', 'LAC', 'LDC', 'LIC', 'LMC', 'LMY', 'MIC', 'MNA', 'SAS', 'SSA', 'UMC']

In [140]:
missing_df = (
    df_IDS_ALLCountries_Data[
        df_IDS_ALLCountries_Data['Country Code'].isin(extra)
    ][['Country Name', 'Country Code']]
    .drop_duplicates()
    .sort_values('Country Name')
)

print(missing_df)

                                            Country Name Country Code
14590        East Asia & Pacific (excluding high income)          EAP
17740                                           Ethiopia          ETH
18206      Europe & Central Asia (excluding high income)          ECA
24419                                           IDA only          IDX
24985                                          IDA total          IDA
30587  Latin America & Caribbean (excluding high income)          LAC
31161       Least developed countries: UN classification          LDC
33043                                Low & middle income          LMY
33617                                         Low income          LIC
34178                                Lower middle income          LMC
38088  Middle East, North Africa, Afghanistan & Pakis...          MNA
38648                                      Middle income          MIC
51035                                         South Asia          SAS
52921         Sub-Saharan Africa (excluding high income)          SSA
59684                                Upper middle income          UMC

In [141]:
df_IDS_ALLCountries_Data = df_IDS_ALLCountries_Data[
    df_IDS_ALLCountries_Data['Country Code'].isin(
        df_IDS_CountryMetaData['Code']
    )
]

In [143]:
df_IDS_ALLCountries_Data['Country Name'].nunique()

119

In [145]:
meta_codes = set(df_IDS_CountryMetaData['Code'].astype(str).str.strip())
main_codes = set(df_IDS_ALLCountries_Data['Country Code'].astype(str).str.strip())

print("Codes in Metadata:", len(meta_codes))
print("Codes in Main Data:", len(main_codes))
print("Common Codes:", len(meta_codes & main_codes))
print("Missing from Main Data:", len(meta_codes - main_codes))

Codes in Metadata: 119
Codes in Main Data: 119
Common Codes: 119
Missing from Main Data: 0

In [148]:
df_IDS_ALLCountries_Data= df_IDS_ALLCountries_Data.drop(columns = 'Country Name')

In [149]:
df_IDS_ALLCountries_Data

,Country Code,Series Name,Series Code,Year,Value
297,ALB,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,1.054540e+01
298,ALB,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,1.054540e+01
299,ALB,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,0.000000e+00
300,ALB,Average grant element on new external debt com...,DT.GRE.DPPG,2000,2.576090e+01
301,ALB,Average grant element on new external debt com...,DT.GRE.OFFT,2000,2.576090e+01
...,...,...,...,...,...
1574517,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,2024,6.881084e+08
1574518,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,2024,6.350490e+06
1574519,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,2024,6.944589e+08
1574520,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2024,0.000000e+00
1574521,ZWE,"Use of IMF credit and SDR allocations (DOD, cu...",DT.DOD.DIMF.CD,2024,1.325023e+09

In [156]:
df_IDS_ALLCountries_Data = df_IDS_ALLCountries_Data.reset_index(drop=True)

In [157]:
df_IDS_ALLCountries_Data

,Country Code,Series Name,Series Code,Year,Value
0,ALB,Average grace period on new external debt comm...,DT.GPA.DPPG,2000,1.054540e+01
1,ALB,Average grace period on new external debt comm...,DT.GPA.OFFT,2000,1.054540e+01
2,ALB,Average grace period on new external debt comm...,DT.GPA.PRVT,2000,0.000000e+00
3,ALB,Average grant element on new external debt com...,DT.GRE.DPPG,2000,2.576090e+01
4,ALB,Average grant element on new external debt com...,DT.GRE.OFFT,2000,2.576090e+01
...,...,...,...,...,...
1050747,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,2024,6.881084e+08
1050748,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,2024,6.350490e+06
1050749,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,2024,6.944589e+08
1050750,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2024,0.000000e+00
1050751,ZWE,"Use of IMF credit and SDR allocations (DOD, cu...",DT.DOD.DIMF.CD,2024,1.325023e+09

In [165]:
df_IDS_ALLCountries_Data= df_IDS_ALLCountries_Data.drop(columns = 'Series Name')

In [166]:
df_IDS_ALLCountries_Data

        Country Code        Series Code  Year         Value
0                ALB        DT.GPA.DPPG  2000  1.054540e+01
1                ALB        DT.GPA.OFFT  2000  1.054540e+01
2                ALB        DT.GPA.PRVT  2000  0.000000e+00
3                ALB        DT.GRE.DPPG  2000  2.576090e+01
4                ALB        DT.GRE.OFFT  2000  2.576090e+01
...              ...                ...   ...           ...
1050747          ZWE     DT.UND.OFFT.CD  2024  6.881084e+08
1050748          ZWE     DT.UND.PRVT.CD  2024  6.350490e+06
1050749          ZWE     DT.UND.DPPG.CD  2024  6.944589e+08
1050750          ZWE  DT.DOD.DIMF.US.CD  2024  0.000000e+00
1050751          ZWE     DT.DOD.DIMF.CD  2024  1.325023e+09

[1050752 rows x 4 columns]

In [162]:
df_IDS_SeriesMetaData = (
    df_IDS_ALLCountries_Data[['Series Code', 'Series Name']]
    .drop_duplicates()
    .reset_index(drop=True))

In [176]:
df_IDS_SeriesMetaData = df_IDS_SeriesMetaData.rename(columns={'Series Name':'Indicator Name'})

In [177]:
df_IDS_SeriesMetaData

             Series Code                                     Indicator Name
0            DT.GPA.DPPG  Average grace period on new external debt comm...
1            DT.GPA.OFFT  Average grace period on new external debt comm...
2            DT.GPA.PRVT  Average grace period on new external debt comm...
3            DT.GRE.DPPG  Average grant element on new external debt com...
4            DT.GRE.OFFT  Average grant element on new external debt com...
..                   ...                                                ...
571  DT.AMT.PBND.PRVG.CD                     PRVG, bonds (AMT, current US$)
572  DT.NFL.PBND.PRVG.CD                     PRVG, bonds (NFL, current US$)
573       DT.DOD.PVLX.CD       Present value of external debt (current US$)
574    DT.DOD.PVLX.EX.ZS  Present value of debt (% of exports of goods, ...
575    DT.DOD.PVLX.GN.ZS                   Present value of debt (% of GNI)

[576 rows x 2 columns]

In [164]:
df_IDS_CountryMetaData

,Country Name,Code,Income Group,Region,Lending category,Is_HIPC
0,Afghanistan,AFG,Low income,Middle East & North Africa,IDA,Yes
1,Albania,ALB,Upper middle income,Europe & Central Asia,IBRD,No
2,Algeria,DZA,Upper middle income,Middle East & North Africa,IBRD,No
3,Angola,AGO,Lower middle income,Sub-Saharan Africa,IBRD,No
4,Argentina,ARG,Upper middle income,Latin America & Caribbean,IBRD,No
...,...,...,...,...,...,...
114,Vanuatu,VUT,Lower middle income,East Asia & Pacific,IDA,No
115,Viet Nam,VNM,Lower middle income,East Asia & Pacific,IBRD,No
116,"Yemen, Republic of",YEM,Low income,Middle East & North Africa,IDA,No
117,Zambia,ZMB,Lower middle income,Sub-Saharan Africa,IDA,Yes
118,Zimbabwe,ZWE,Lower middle income,Sub-Saharan Africa,Blend,No

In [170]:
df_IDS_ALLCountries_Data.to_csv('Debt_Data.csv',index = False)

In [171]:
df_IDS_CountryMetaData.to_csv('Country_Details.csv',index = False)

In [178]:
df_IDS_SeriesMetaData.to_csv('Indicator_Details.csv',index = False)